# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CiderHouseRestaurantWaiter' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'MBProgressHUD', '~> 1.1.0'
  # Pods for CiderHouseRestaurantWaiter

  target 'CiderHouseRestaurantWaiterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CiderHouseRestaurantWaiterUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
